### ISSUE TITLE
CAP_NET_BIND_SERVICE needed

### ISSUE THREAD

**Issue by techotaku** [chenhw2/https-dns#1]
To listen on port 53, `CAP_NET_BIND_SERVICE` is required.    

Could you help to add below commands to `Dockerfile`? Thanks. 
```
apk add --update --no-cache libcap
setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/google-https-dns
apk del libcap
```

**Comment by honwen** [comment]
To listen on port 53, recommend solution:
```
docker run -d \
    -e "ARGS=-d 8.8.8.8 --edns 0.0.0.0/0" \
    -p "53:5300/udp" \
    -p "53:5300/tcp" \
    chenhw2/google-https-dns
```

Let host OS deal with CAPs.

**Comment by techotaku** [comment]
Got it. Partially solve the problem.  **Thanks.**

P.S. I have two situations need port 53:  
1. Remote client need.  
2. Local service need a private resolver but cannot set port.  

But there're some other approach for situation 2.

**Comment by honwen** [comment]
Local service?
For example, Docker of this get ip 172.17.0.X, ```google-https-dns``` listen on 5300,
with ```  -p "53:5300/udp" -p "53:5300/tcp" ```
172.17.0.1:53 can service local as well.

**Comment by techotaku** [comment]
Yeah, so I said "there're some other approach" :)
